#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.Serialization;



[System.Data.Linq.Mapping.DatabaseAttribute(Name="int422_101b17")]
public partial class DigitalDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  #endregion
	
	public DigitalDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["int422_101b17ConnectionString2"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DigitalDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DigitalDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DigitalDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DigitalDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<DigitalContent> DigitalContents
	{
		get
		{
			return this.GetTable<DigitalContent>();
		}
	}
}

[Table(Name="dbo.DigitalContent")]
[DataContract()]
public partial class DigitalContent
{
	
	private int _ItemID;
	
	private System.Nullable<System.DateTime> _DateTimeStamp;
	
	private string _MIMEType;
	
	private string _Title;
	
	private System.Data.Linq.Binary _Content;
	
	public DigitalContent()
	{
	}
	
	[Column(Storage="_ItemID", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
	[DataMember(Order=1)]
	public int ItemID
	{
		get
		{
			return this._ItemID;
		}
		set
		{
			if ((this._ItemID != value))
			{
				this._ItemID = value;
			}
		}
	}
	
	[Column(Storage="_DateTimeStamp", DbType="DateTime")]
	[DataMember(Order=2)]
	public System.Nullable<System.DateTime> DateTimeStamp
	{
		get
		{
			return this._DateTimeStamp;
		}
		set
		{
			if ((this._DateTimeStamp != value))
			{
				this._DateTimeStamp = value;
			}
		}
	}
	
	[Column(Storage="_MIMEType", DbType="VarChar(50)")]
	[DataMember(Order=3)]
	public string MIMEType
	{
		get
		{
			return this._MIMEType;
		}
		set
		{
			if ((this._MIMEType != value))
			{
				this._MIMEType = value;
			}
		}
	}
	
	[Column(Storage="_Title", DbType="VarChar(50)")]
	[DataMember(Order=4)]
	public string Title
	{
		get
		{
			return this._Title;
		}
		set
		{
			if ((this._Title != value))
			{
				this._Title = value;
			}
		}
	}
	
	[Column(Storage="_Content", DbType="Image", CanBeNull=true, UpdateCheck=UpdateCheck.Never)]
	[DataMember(Order=5)]
	public System.Data.Linq.Binary Content
	{
		get
		{
			return this._Content;
		}
		set
		{
			if ((this._Content != value))
			{
				this._Content = value;
			}
		}
	}
}
#pragma warning restore 1591
