<?xml version="1.0" encoding="utf-8"?>
<Database Name="int422_101b17" Class="DigitalDataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=mssql.warp.senecac.on.ca;Initial Catalog=int422_101b17;Persist Security Info=True;User ID=int422_101b17" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="int422_101b17ConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.DigitalContent" Member="DigitalContents">
    <Type Name="DigitalContent">
      <Column Name="ItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DateTimeStamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MIMEType" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Content" Type="System.Data.Linq.Binary" DbType="Image" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>